site_name: Nara's Blog
site_url: 'http://narayaruna.github.io/'
repo_url: 'https://github.com/narayaruna/narayaruna.github.io'
edit_uri: ''
site_description: Sharing my learnings 
site_author: Narayanan Arunachalam
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
google_analytics: ['UA-........-.', 'narayaruna.github.io']
remote_branch: master

strict: True

pages:
- Home: index.md

theme: material

extra:
  font:
    code: 'Menlo'

extra_css:
- css/custom.css

markdown_extensions:
- admonition
- codehilite
- pymdownx.tilde
- toc:
    permalink: True
